varwin/blockly

README.md, core/field_dropdown.js
- Disable feature factor out common words in statically defined options.
=> Disable feature factor out common words in options

README.md, core/field_dropdown.js, core/xml.js, package.json
Feature
- Option out affix in dropdown (VRWN-4944)
- Update readme
- Not show dropdown for one option (VRWN-4943)
- Fix applyNextTagNodes  (VRWN-4739)
=> Option out affix in dropdown

core/field_dropdown.js, package.json
=> Fix check option dropdown

core/field_colour.js, package.json
VRWN-4926
- Add chessboard substrate for field colour
=> Add chessboard substrate for field colour

core/field.js, core/field_multilineinput.js
VRWN-5082
- Remove ellipsis in text block
=> Remove ellipsis in text block

core/module_manager.js, core/modulebar.js, core/shortcut_items.js
=> Feature: add duplicate shortcut

core/block_dragger.js, core/flyout_base.js, core/toolbox/toolbox.js
=> fix delete block on drag

core/block_svg.js, core/connection_checker.js, core/field_label_hover.js, core/gesture.js, package.json, scripts/gulpfiles/chunks.json
- fix def argument local as shadow
=> fix def argument local as shadow

blocks/loops.js, package.json
- Add new blocks loop with arguments
=> Add new blocks loop with arguments

core/field_label_hover.js, package.json
- Add xml method for FieldLabelHover
=> Extend field label hover

core/mass_operations/mass_operation_handlers.js, package.json
and remove redundant gesture disposes
=> Add change listener for check module switching

blocks/argument_local.js, core/flyout_base.js, core/procedures_local_arguments.js, core/workspace_svg.js, package.json
- update open flyout
- fix show close button flyout
=> update open flyout

blocks/procedures_local_argument.js, core/procedures_local_arguments.js, package.json
- fix create procedures call
VRWN-5248
=> fix create procedures call

blocks/argument_local.js, blocks/procedures_local_argument.js, core/procedures_local_arguments.js
VRWN-5254
- Fix procedures local argument
=> Fix procedures local argument

core/contextmenu.js, core/field.js, package.json
- Fix translate name page in context menu (VRWN-5142)
- Fix max display length for field (VRWN-5235)
=> Fix translate and max length field

core/field_label_hover.js, package.json
VRWN-5314
- Fix apply colour for label hover
=> Fix apply colour for label hover

core/block_svg.js, core/module_manager.js, core/xml.js, package.json
- fix deprecated warnings
- remove extra "for"s
=> Bugfix: deprecated warnings

core/common.js, package.json
- fix svgResize with 0 height
- update package version
=> Bugfix: svgResize with 0 height

blocks/procedures_local_argument.js, package.json
Add varid for argument in call procedures local arguments
=> Add varid for argument in call procedures local

core/module_manager.js, core/modulebar.js, package.json
VRWN-5488
- remove deprecated func
- fix scope with var/let
=> Remove deprecated func, fix scope

core/events/events_module_activate.js, core/events/events_module_create.js, core/events/events_module_delete.js, core/modulebar.js, package.json
VRWN-5739
- block handle change module in loading
=> block handle change module in loading

core/field_dropdown.js, package.json
VRWN-5873
- Move rename var option on first position
=> Move rename var option on first position

core/contextmenu.js, core/mass_operations/mass_operation_handlers.js, core/module_model.js
- fix module name translation in context menu
=> fix module name translation in context menu

core/field_multilineinput.js
VRWN-5507
- fix multiline text width when copy parent block
=> fix multiline text width when copy parent block

core/field_dropdown.js
VRWN-5873
- fix sort options in dropdown
=> fix sort options in dropdown

core/field.js, core/field_multilineinput.js, core/field_textinput.js
VRWN-6000
- Add limit for field text input
=> Add limit for field text input

core/css.js, package.json
=> Fix flicker flyout bookmark cn lang

core/workspace_svg.js, package.json
VRWN-6103
fix paste block in center of view
=> fix paste block in center of view

core/block_svg.js, core/contextmenu.js, core/events/events_module_create.js, core/events/events_module_delete.js, msg/json/en.json, msg/json/qqq.json, msg/json/ru.json, msg/json/zh-hant.json, msg/messages.js, package.json
VRWN-6148
- add option in context menu move block to new module
=> context menu move block to new module

core/field_textinput.js
- Add filter in textinput for bad xml chars
=> Add filter in textinput for bad xml chars

core/field_dropdown.js, package.json
hotfix dropdown block not removed
=> hotfix dropdown block not removed

core/css.js, package.json
VRWN-6508
- fix white-space for flyout bookmark
=> fix white-space for flyout bookmark

README.md, core/block.js, package.json
- fix unknown block type error
- update readme.md
=> fix unknown block type error

package.json
- bump version to 8.20220705.36
=> bump version to 8.20220705.36
